import type { DemoState, Shift } from "./types";

const employeeEligibility =
  "Active Pick n Pay retail employee at the listed site";

function createShift(
  id: string,
  date: string,
  startTime: string,
  endTime: string,
  site: string,
  role: string,
  estimatedEarnings: number,
  deadline: string | null,
  status: Shift["status"],
  transport: string,
  applications: number,
  spots: number,
): Shift {
  return {
    id,
    date,
    startTime,
    endTime,
    site,
    role,
    estimatedEarnings,
    estimateKind:
      status === "confirmed"
        ? "confirmed_before_deductions"
        : "estimated_before_deductions",
    deadline,
    status,
    transport,
    eligibility: employeeEligibility,
    applications,
    spots,
  };
}

export function createInitialDemoState(): DemoState {
  return {
    mode: "employee",
    actorSession: {
      actorId: "employee",
      displayName: "Nomsa Dlamini",
      policyRevision: 1,
    },
    revision: 1,
    auditEvents: [],
    proposals: [],
    savingsIntent: null,
    onboarding: { completed: true, step: 1 },
    employee: {
      activeTab: "overview",
      profile: {
        firstName: "Nomsa",
        fullName: "Nomsa Dlamini",
        employerName: "Pick n Pay Retail",
        role: "Senior Sales Associate",
        hourlyRate: 62.5,
        payFrequency: "monthly",
        nextPayday: "2026-09-05",
        daysToPayday: 8,
        expectedEarnings: 4800,
        hoursWorked: 76,
        startDate: "2026-02-12",
      },
      goal: {
        name: "School Fees",
        emoji: "🎓",
        targetAmount: 6000,
        savedAmount: 2520,
        targetDate: "2026-12-01",
        monthlyContribution: 400,
        isPrivate: true,
      },
      expenses: {
        housing: 1200,
        transport: 450,
        food: 800,
        dependants: 600,
        debt: 300,
        airtime: 150,
        other: 100,
      },
      shifts: [
        createShift(
          "shift-mon-rosebank",
          "2026-08-31",
          "08:00",
          "17:00",
          "Rosebank Mall",
          "Sales Floor",
          500,
          null,
          "confirmed",
          "Minibus taxi stop outside",
          0,
          1,
        ),
        createShift(
          "shift-tue-rosebank",
          "2026-09-01",
          "08:00",
          "17:00",
          "Rosebank Mall",
          "Sales Floor",
          500,
          null,
          "confirmed",
          "Minibus taxi stop outside",
          0,
          1,
        ),
        createShift(
          "shift-wed-rosebank",
          "2026-09-02",
          "08:00",
          "17:00",
          "Rosebank Mall",
          "Sales Floor",
          500,
          null,
          "confirmed",
          "Minibus taxi stop outside",
          0,
          1,
        ),
        createShift(
          "shift-fri-rosebank",
          "2026-09-04",
          "08:00",
          "17:00",
          "Rosebank Mall",
          "Sales Floor",
          500,
          null,
          "confirmed",
          "Minibus taxi stop outside",
          0,
          1,
        ),
        createShift(
          "shift-sat-rosebank",
          "2026-09-05",
          "08:00",
          "17:00",
          "Rosebank Mall",
          "Sales Floor",
          480,
          "2026-09-04",
          "available",
          "Minibus taxi stop outside",
          3,
          2,
        ),
        createShift(
          "shift-thu-sandton",
          "2026-09-03",
          "14:00",
          "21:00",
          "Sandton City",
          "Evening Cover",
          360,
          "2026-09-03",
          "requested",
          "Gautrain accessible",
          1,
          1,
        ),
        createShift(
          "shift-sun-rosebank",
          "2026-09-06",
          "09:00",
          "15:00",
          "Rosebank Mall",
          "Weekend Cover",
          300,
          "2026-09-05",
          "available",
          "Minibus taxi stop outside",
          0,
          3,
        ),
      ],
      learning: [
        {
          id: "learning-budgeting",
          title: "Smart Budgeting & Emergency Fund Basics",
          description: "Build a practical budget and start an emergency fund.",
          category: "Financial Literacy",
          durationMinutes: 8,
          rewardAmount: 100,
          rewardType: "voucher",
          completed: true,
          expiresOn: "2026-09-30",
        },
        {
          id: "learning-payslip",
          title: "Demystifying Your Payslip: UIF, PAYE & Deductions",
          description:
            "Understand gross versus net pay, UIF and PAYE deductions.",
          category: "Financial Literacy",
          durationMinutes: 6,
          rewardAmount: 75,
          rewardType: "voucher",
          completed: false,
          expiresOn: "2026-09-30",
        },
        {
          id: "learning-safety",
          title: "Occupational Health & Retail Floor Safety",
          description:
            "Practise safe lifting and hazard reporting on the retail floor.",
          category: "Workplace Safety",
          durationMinutes: 12,
          rewardAmount: 200,
          rewardType: "cash",
          completed: false,
          expiresOn: "2026-10-15",
        },
      ],
      rewards: [
        {
          id: "reward-reliability",
          title: "September Reliability Award",
          description: "Earn a cash reward for reliable September attendance.",
          amount: 250,
          rewardType: "cash",
          qualifying: 3,
          required: 5,
          status: "in_progress",
          deadline: "2026-09-30",
          allocatedTo: null,
        },
        {
          id: "reward-literacy",
          title: "Financial Literacy Completion",
          description: "Complete the financial literacy learning pathway.",
          amount: 100,
          rewardType: "voucher",
          qualifying: null,
          required: null,
          status: "in_progress",
          deadline: "2026-09-30",
          allocatedTo: null,
        },
        {
          id: "reward-safety",
          title: "August Safety Award",
          description: "Recognises safe work practices during August.",
          amount: 150,
          rewardType: "cash",
          qualifying: null,
          required: null,
          status: "earned",
          deadline: null,
          allocatedTo: null,
        },
      ],
    },
    employer: {
      activeTab: "dashboard",
      profile: {
        employerName: "Pick n Pay Retail",
        contactName: "Sipho Khumalo",
        role: "HR Manager",
        totalEmployees: 847,
        activeEmployees: 612,
        goalEngagementPercent: 68,
        dataConfidencePercent: 87,
      },
      programmes: [
        {
          id: "programme-reliability",
          name: "September Reliability Reward",
          type: "attendance",
          budget: 50000,
          spent: 18750,
          enrolled: 247,
          participating: 189,
          status: "active",
          readiness: "ready",
          expiresOn: "2026-09-30",
        },
        {
          id: "programme-safety",
          name: "Safety Learning Pathway",
          type: "learning",
          budget: 30000,
          spent: 8200,
          enrolled: 312,
          participating: 82,
          status: "active",
          readiness: "ready",
          expiresOn: "2026-10-15",
        },
        {
          id: "programme-open-shifts",
          name: "Q4 Open Shifts Incentive",
          type: "extra_shifts",
          budget: 75000,
          spent: 0,
          enrolled: 0,
          participating: 0,
          status: "draft",
          readiness: "review_required",
          expiresOn: null,
        },
      ],
      fairnessExceptions: [
        {
          id: "exception-attendance-conflict",
          employeeLabel: "N. Dlamini",
          issue:
            "Attendance record conflicts with published roster for 2026-08-28",
          programmeName: "September Reliability Reward",
          severity: "medium",
          recordFreshnessHours: 12,
          reviewState: "open",
        },
        {
          id: "exception-missing-clock-in",
          employeeLabel: "T. Mokoena",
          issue: "No clock-in logged for confirmed shift on 2026-08-25",
          programmeName: "September Reliability Reward",
          severity: "medium",
          recordFreshnessHours: 18,
          reviewState: "open",
        },
        {
          id: "exception-missing-leave",
          employeeLabel: "L. Ndlovu",
          issue: "Leave approval missing for absence on 2026-08-20",
          programmeName: "Safety Learning Pathway",
          severity: "low",
          recordFreshnessHours: 30,
          reviewState: "open",
        },
      ],
      fairnessRules: [
        "Approved sick leave never counts against attendance-based rewards.",
        "Employer-initiated shift changes cannot disqualify an employee.",
        "Clocking system failures enter manager review, not automatic disqualification.",
        "Employees have 14 days to raise eligibility disputes after notification.",
        "Reward calculations require source data less than 48 hours old.",
        "No reward may be issued from conflicting or unverified records.",
      ],
      activeDraft: null,
      validation: null,
    },
    activity: null,
  };
}
